### ISSUE TITLE
Bundle `blended.activemq.defaultbroker`cannot be started when offline

### ISSUE THREAD

**Issue by lefou** [woq-blended/blended#56]
```
org.osgi.framework.BundleException: Activator start error in bundle blended.activemq.defaultbroker [103].
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2270)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2138)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977)
        at org.apache.felix.gogo.command.Basic.start(Basic.java:729)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
        at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
        at org.apache.felix.gogo.shell.Console.run(Console.java:62)
        at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)
        at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
        at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
        at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 25 in XML document from file [/home/lefou/work/woq/blended/blended-launcher-demo/profiles/blended-demo/1.2-SNAPSHOT/etc/broker.amq] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 25; columnNumber: 11; cvc-elt.1: Deklaration des Elements "beans" kann nicht gefunden werden.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:396)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
        at org.apache.xbean.spring.context.ResourceXmlApplicationContext.loadBeanDefinitions(ResourceXmlApplicationContext.java:111)
        at org.apache.xbean.spring.context.ResourceXmlApplicationContext.loadBeanDefinitions(ResourceXmlApplicationContext.java:104)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:537)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451)
        at org.apache.xbean.spring.context.ResourceXmlApplicationContext.<init>(ResourceXmlApplicationContext.java:64)
        at org.apache.xbean.spring.context.ResourceXmlApplicationContext.<init>(ResourceXmlApplicationContext.java:52)
        at org.apache.activemq.xbean.XBeanBrokerFactory$1.<init>(XBeanBrokerFactory.java:104)
        at org.apache.activemq.xbean.XBeanBrokerFactory.createApplicationContext(XBeanBrokerFactory.java:104)
        at org.apache.activemq.xbean.XBeanBrokerFactory.createBroker(XBeanBrokerFactory.java:67)
        at blended.activemq.brokerstarter.BrokerActivator$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(BrokerActivator.scala:55)
        at blended.activemq.brokerstarter.BrokerActivator$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(BrokerActivator.scala:35)
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1$$anonfun$1.apply$mcV$sp(TypesafeConfigCapsule.scala:30)
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1$$anonfun$1.apply(TypesafeConfigCapsule.scala:30)
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1$$anonfun$1.apply(TypesafeConfigCapsule.scala:30)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at domino.capsule.DynamicCapsuleContext$class.executeWithinNewCapsuleScope(DynamicCapsuleContext.scala:33)
        at domino.DominoActivator.executeWithinNewCapsuleScope(DominoActivator.scala:67)
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1.apply(TypesafeConfigCapsule.scala:29)
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1.apply(TypesafeConfigCapsule.scala:24)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$1.apply$mcV$sp(ServiceWatching.scala:85)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$1.apply(ServiceWatching.scala:85)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$1.apply(ServiceWatching.scala:85)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at domino.capsule.DynamicCapsuleContext$class.executeWithinNewCapsuleScope(DynamicCapsuleContext.scala:33)
        at domino.DominoActivator.executeWithinNewCapsuleScope(DominoActivator.scala:67)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:84)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:80)
        at domino.service_watching.ServiceWatcherCapsule$$anon$1.addingService(ServiceWatcherCapsule.scala:35)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:932)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:864)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:317)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
        at domino.service_watching.ServiceWatcherCapsule.start(ServiceWatcherCapsule.scala:51)
        at domino.capsule.DynamicCapsuleContext$class.addCapsule(DynamicCapsuleContext.scala:22)
        at domino.DominoActivator.addCapsule(DominoActivator.scala:67)
        at domino.service_watching.ServiceWatching$class.watchAdvancedServices(ServiceWatching.scala:50)
        at blended.domino.internal.TypesafeConfigCapsule.watchAdvancedServices(TypesafeConfigCapsule.scala:11)
        at domino.service_watching.ServiceWatching$class.whenAdvancedServicePresent(ServiceWatching.scala:80)
        at blended.domino.internal.TypesafeConfigCapsule.whenAdvancedServicePresent(TypesafeConfigCapsule.scala:11)
        at domino.service_watching.ServiceWatching$class.whenServicePresent(ServiceWatching.scala:65)
        at blended.domino.internal.TypesafeConfigCapsule.whenServicePresent(TypesafeConfigCapsule.scala:11)
        at blended.domino.internal.TypesafeConfigCapsule.start(TypesafeConfigCapsule.scala:24)
        at domino.capsule.DynamicCapsuleContext$class.addCapsule(DynamicCapsuleContext.scala:22)
        at domino.DominoActivator.addCapsule(DominoActivator.scala:67)
        at blended.domino.TypesafeConfigWatching$class.whenTypesafeConfigAvailable(TypesafeConfigWatching.scala:20)
        at blended.activemq.brokerstarter.BrokerActivator.whenTypesafeConfigAvailable(BrokerActivator.scala:31)
        at blended.activemq.brokerstarter.BrokerActivator$$anonfun$1.apply$mcV$sp(BrokerActivator.scala:35)
        at blended.activemq.brokerstarter.BrokerActivator$$anonfun$1.apply(BrokerActivator.scala:35)
        at blended.activemq.brokerstarter.BrokerActivator$$anonfun$1.apply(BrokerActivator.scala:35)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at domino.capsule.DynamicCapsuleContext$class.executeWithinNewCapsuleScope(DynamicCapsuleContext.scala:33)
        at domino.DominoActivator.executeWithinNewCapsuleScope(DominoActivator.scala:67)
        at domino.OsgiContext$$anonfun$start$1.apply(OsgiContext.scala:60)
        at domino.OsgiContext$$anonfun$start$1.apply(OsgiContext.scala:58)
        at scala.Option.foreach(Option.scala:236)
        at domino.OsgiContext$class.start(OsgiContext.scala:58)
        at domino.DominoActivator.start(DominoActivator.scala:67)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2220)
        ... 32 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 25; columnNumber: 11; cvc-elt.1: Deklaration des Elements "beans" kann nicht gefunden werden.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1906)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:605)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3138)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
        at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:388)
        ... 96 more
```

**Comment by lefou** [comment]
This SO answer might help: http://stackoverflow.com/questions/25365998/org-springframework-beans-factory-xml-xmlbeandefinitionstoreexception-in-spring
