### ISSUE TITLE
blended.demo.mgmt: Missing or invalid configuration. Cannot provide file base artifact repository

### ISSUE THREAD

**Issue by lefou** [woq-blended/blended#89]
From the log file of the `blended.demo.mgmt` container:

```
Missing or invalid configuration. Cannot provide file base artifact repository. See error message for details.
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'repoId'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152) ~[config-1.3.1.jar:na]
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170) ~[config-1.3.1.jar:na]
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184) ~[config-1.3.1.jar:na]
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189) ~[config-1.3.1.jar:na]
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246) ~[config-1.3.1.jar:na]
        at blended.mgmt.repo.internal.ArtifactRepoActivator$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ArtifactRepoActivator.scala:25) [blended.mgmt.repo-2.1.0-SNAPSHOT.jar:na]
        at blended.mgmt.repo.internal.ArtifactRepoActivator$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ArtifactRepoActivator.scala:21) [blended.mgmt.repo-2.1.0-SNAPSHOT.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1$$anonfun$1.apply$mcV$sp(TypesafeConfigCapsule.scala:30) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1$$anonfun$1.apply(TypesafeConfigCapsule.scala:30) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1$$anonfun$1.apply(TypesafeConfigCapsule.scala:30) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) [scala-library-2.11.11.jar:na]
        at domino.capsule.DynamicCapsuleContext$class.executeWithinNewCapsuleScope(DynamicCapsuleContext.scala:33) [domino_2.11-1.1.1.jar:na]
        at domino.DominoActivator.executeWithinNewCapsuleScope(DominoActivator.scala:66) [domino_2.11-1.1.1.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1.apply(TypesafeConfigCapsule.scala:29) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule$$anonfun$start$1.apply(TypesafeConfigCapsule.scala:24) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$1.apply$mcV$sp(ServiceWatching.scala:85) [domino_2.11-1.1.1.jar:na]
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$1.apply(ServiceWatching.scala:85) [domino_2.11-1.1.1.jar:na]
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$1.apply(ServiceWatching.scala:85) [domino_2.11-1.1.1.jar:na]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) [scala-library-2.11.11.jar:na]
        at domino.capsule.DynamicCapsuleContext$class.executeWithinNewCapsuleScope(DynamicCapsuleContext.scala:33) [domino_2.11-1.1.1.jar:na]
        at domino.DominoActivator.executeWithinNewCapsuleScope(DominoActivator.scala:66) [domino_2.11-1.1.1.jar:na]
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:84) [domino_2.11-1.1.1.jar:na]
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:80) [domino_2.11-1.1.1.jar:na]
        at domino.service_watching.ServiceWatcherCapsule$$anon$1.addingService(ServiceWatcherCapsule.scala:35) [domino_2.11-1.1.1.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:932) [org.osgi.core-5.0.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:864) [org.osgi.core-5.0.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.osgi.core-5.0.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) [org.osgi.core-5.0.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:317) [org.osgi.core-5.0.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261) [org.osgi.core-5.0.0.jar:na]
        at domino.service_watching.ServiceWatcherCapsule.start(ServiceWatcherCapsule.scala:51) [domino_2.11-1.1.1.jar:na]
        at domino.capsule.DynamicCapsuleContext$class.addCapsule(DynamicCapsuleContext.scala:22) [domino_2.11-1.1.1.jar:na]
        at domino.DominoActivator.addCapsule(DominoActivator.scala:66) [domino_2.11-1.1.1.jar:na]
        at domino.service_watching.ServiceWatching$class.watchAdvancedServices(ServiceWatching.scala:50) [domino_2.11-1.1.1.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule.watchAdvancedServices(TypesafeConfigCapsule.scala:11) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at domino.service_watching.ServiceWatching$class.whenAdvancedServicePresent(ServiceWatching.scala:80) [domino_2.11-1.1.1.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule.whenAdvancedServicePresent(TypesafeConfigCapsule.scala:11) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at domino.service_watching.ServiceWatching$class.whenServicePresent(ServiceWatching.scala:65) [domino_2.11-1.1.1.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule.whenServicePresent(TypesafeConfigCapsule.scala:11) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at blended.domino.internal.TypesafeConfigCapsule.start(TypesafeConfigCapsule.scala:24) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at domino.capsule.DynamicCapsuleContext$class.addCapsule(DynamicCapsuleContext.scala:22) [domino_2.11-1.1.1.jar:na]
        at domino.DominoActivator.addCapsule(DominoActivator.scala:66) [domino_2.11-1.1.1.jar:na]
        at blended.domino.TypesafeConfigWatching$class.whenTypesafeConfigAvailable(TypesafeConfigWatching.scala:20) [blended.domino-2.1.0-SNAPSHOT.jar:na]
        at blended.mgmt.repo.internal.ArtifactRepoActivator.whenTypesafeConfigAvailable(ArtifactRepoActivator.scala:14) [blended.mgmt.repo-2.1.0-SNAPSHOT.jar:na]
        at blended.mgmt.repo.internal.ArtifactRepoActivator$$anonfun$1.apply$mcV$sp(ArtifactRepoActivator.scala:21) [blended.mgmt.repo-2.1.0-SNAPSHOT.jar:na]
        at blended.mgmt.repo.internal.ArtifactRepoActivator$$anonfun$1.apply(ArtifactRepoActivator.scala:18) [blended.mgmt.repo-2.1.0-SNAPSHOT.jar:na]
        at blended.mgmt.repo.internal.ArtifactRepoActivator$$anonfun$1.apply(ArtifactRepoActivator.scala:18) [blended.mgmt.repo-2.1.0-SNAPSHOT.jar:na]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) [scala-library-2.11.11.jar:na]
        at domino.capsule.DynamicCapsuleContext$class.executeWithinNewCapsuleScope(DynamicCapsuleContext.scala:33) [domino_2.11-1.1.1.jar:na]
        at domino.DominoActivator.executeWithinNewCapsuleScope(DominoActivator.scala:66) [domino_2.11-1.1.1.jar:na]
        at domino.OsgiContext$$anonfun$start$1.apply(OsgiContext.scala:60) [domino_2.11-1.1.1.jar:na]
        at domino.OsgiContext$$anonfun$start$1.apply(OsgiContext.scala:58) [domino_2.11-1.1.1.jar:na]
        at scala.Option.foreach(Option.scala:257) [scala-library-2.11.11.jar:na]
        at domino.OsgiContext$class.start(OsgiContext.scala:58) [domino_2.11-1.1.1.jar:na]
        at domino.DominoActivator.start(DominoActivator.scala:66) [domino_2.11-1.1.1.jar:na]
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) [org.apache.felix.framework-5.0.0.jar:na]
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2220) [org.apache.felix.framework-5.0.0.jar:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2138) [org.apache.felix.framework-5.0.0.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977) [org.apache.felix.framework-5.0.0.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:964) [org.apache.felix.framework-5.0.0.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1$$anonfun$12$$anonfun$1.apply$mcV$sp(Launcher.scala:438) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1$$anonfun$12$$anonfun$1.apply(Launcher.scala:438) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1$$anonfun$12$$anonfun$1.apply(Launcher.scala:438) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.11.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1$$anonfun$12.apply(Launcher.scala:437) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1$$anonfun$12.apply(Launcher.scala:436) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) [scala-library-2.11.11.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) [scala-library-2.11.11.jar:na]
        at scala.collection.immutable.List.foreach(List.scala:392) [scala-library-2.11.11.jar:na]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) [scala-library-2.11.11.jar:na]
        at scala.collection.immutable.List.map(List.scala:296) [scala-library-2.11.11.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1.apply$mcVI$sp(Launcher.scala:436) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1.apply(Launcher.scala:424) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher$$anonfun$start$1.apply(Launcher.scala:424) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) [scala-library-2.11.11.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) [scala-library-2.11.11.jar:na]
        at scala.collection.immutable.Range.foreach(Range.scala:160) [scala-library-2.11.11.jar:na]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) [scala-library-2.11.11.jar:na]
        at scala.collection.AbstractTraversable.map(Traversable.scala:104) [scala-library-2.11.11.jar:na]
        at blended.launcher.Launcher.start(Launcher.scala:424) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher.run(Launcher.scala:474) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher$.run(Launcher.scala:209) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher$.main(Launcher.scala:104) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
        at blended.launcher.Launcher.main(Launcher.scala) [blended.launcher-2.1.0-SNAPSHOT.jar:na]
INFO
```

**Comment by lefou** [comment]
Fixed meanwhile
